.PHONY: help lint template render env-config test all

CHART       ?= chart
ENV         ?= aks-test
VALUES      ?= $(CHART)/values-$(ENV).yaml
FOUNDATION  ?= ../plat-eng-aks-foundation/aks-foundation
RENDER_OUT  ?= render-out

# Default target
help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

lint: ## helm lint the control-plane chart
	helm lint $(CHART) --values $(VALUES)

template: ## Render the chart to stdout
	@helm template control-plane $(CHART) --values $(VALUES)

## Validates the TOP-LEVEL objects against the CRDs actually installed in the cluster.
##
## Know its blind spot: the managed resources inside a Composition's `input.resources[].base`
## are opaque to the API server — it validates the Composition, not what the Composition would
## create. A base with a nonexistent field passes here. `make render` plus a real XR is what
## catches that.
##
## kubeconform is deliberately not used: it has no schemas for Crossplane types and reports
## every resource "Skipped", which reads like a pass while checking nothing.
test: ## Server-side dry-run the rendered manifests against the live CRDs (needs cluster access)
	@helm template control-plane $(CHART) --values $(VALUES) | \
		kubectl apply --dry-run=server -f -

## Offline Composition check: runs the real functions locally (via Docker) and prints the
## managed resources a Composition would actually create. This is the only local check that
## sees inside a Composition — `make test` cannot (see its note above).
##
## crossplane render takes ONE Composition, a functions file, and needs the EnvironmentConfig
## passed as an extra resource, so the chart output is split apart first. Rendering the whole
## chart at it fails with "not a composition: ClusterProviderConfig/default".
render: ## crossplane render each Composition against its example XR
	@command -v crossplane >/dev/null || { echo "crossplane CLI (v2+) is required"; exit 1; }
	@mkdir -p $(RENDER_OUT)
	@helm template control-plane $(CHART) --values $(VALUES) > $(RENDER_OUT)/all.yaml
	@yq ea 'select(.kind == "Function")' $(RENDER_OUT)/all.yaml > $(RENDER_OUT)/functions.yaml
	@yq ea 'select(.kind == "EnvironmentConfig")' $(RENDER_OUT)/all.yaml > $(RENDER_OUT)/envconfig.yaml
	@# render executes functions locally rather than in-cluster; it needs to be told how.
	@yq -i '.metadata.annotations."render.crossplane.io/runtime" = "Docker"' $(RENDER_OUT)/functions.yaml
	@rc=0; for xr in examples/*.yaml; do \
		kind=$$(yq e '.kind' $$xr); \
		name=$$(basename $$xr .yaml); \
		yq ea "select(.kind == \"Composition\" and .spec.compositeTypeRef.kind == \"$$kind\")" \
			$(RENDER_OUT)/all.yaml > $(RENDER_OUT)/$$name-composition.yaml; \
		[ -s $(RENDER_OUT)/$$name-composition.yaml ] || { echo "FAIL $$name: no Composition for kind $$kind"; rc=1; continue; }; \
		echo "--- render: $$name ($$kind)"; \
		if crossplane render $$xr \
			$(RENDER_OUT)/$$name-composition.yaml \
			$(RENDER_OUT)/functions.yaml \
			--extra-resources=$(RENDER_OUT)/envconfig.yaml \
			> $(RENDER_OUT)/$$name.rendered.yaml 2>$(RENDER_OUT)/$$name.err; then \
			grep -E '^kind:' $(RENDER_OUT)/$$name.rendered.yaml | sed 's/^/      /'; \
		else \
			echo "FAIL $$name:"; sed 's/^/      /' $(RENDER_OUT)/$$name.err; rc=1; \
		fi; \
	done; exit $$rc

## Regenerate the per-environment EnvironmentConfig values from Terraform.
## These IDs are owned by plat-eng-aks-foundation; never hand-edit values-$(ENV).yaml.
## Outputs are read one at a time on purpose. `terraform output -json` with no name emits every
## output including generated SSH keys, whose raw control characters make the document
## unparseable by jq.
env-config: ## Regenerate chart/values-$(ENV).yaml from terraform output
	@command -v jq >/dev/null || { echo "jq is required"; exit 1; }
	@test -d $(FOUNDATION) || { echo "foundation not found at $(FOUNDATION)"; exit 1; }
	@echo "Reading terraform outputs from $(FOUNDATION) ..."
	@pg_subnet=$$(cd $(FOUNDATION) && terraform output -raw postgres_flexibleserver_subnet_id 2>/dev/null); \
	pg_zone=$$(cd $(FOUNDATION) && terraform output -raw postgres_flexibleserver_private_dns_zone_id 2>/dev/null); \
	pe_subnet=$$(cd $(FOUNDATION) && terraform output -raw private_endpoints_subnet_id 2>/dev/null); \
	redis_zone=$$(cd $(FOUNDATION) && terraform output -json private_dns_zone_ids 2>/dev/null | jq -r '.["privatelink.redis.cache.windows.net"] // empty'); \
	for v in pg_subnet pg_zone pe_subnet redis_zone; do \
		eval "val=\$$$$v"; \
		[ -n "$$val" ] || { echo "ERROR: terraform output for $$v is empty — has 'terraform apply' run in $(FOUNDATION)?"; exit 1; }; \
	done; \
	{ \
		echo "# GENERATED by 'make env-config ENV=$(ENV)'. Do not hand-edit."; \
		echo "# Source: terraform output ($(FOUNDATION)), environment $(ENV)."; \
		echo "# These IDs are owned by plat-eng-aks-foundation. If a subnet or private-DNS"; \
		echo "# zone is recreated, re-run this target — a stale ID surfaces as an XR that"; \
		echo "# never reaches Ready."; \
		echo ""; \
		echo "environmentConfig:"; \
		echo "  postgresSubnetId: $$pg_subnet"; \
		echo "  postgresZoneId: $$pg_zone"; \
		echo "  peSubnetId: $$pe_subnet"; \
		echo "  redisZoneId: $$redis_zone"; \
	} > $(VALUES)
	@echo "Wrote $(VALUES)"

all: lint test render ## Run every local check
