.PHONY: help lint template render env-config test all

CHART       ?= chart
ENV         ?= aks-test
VALUES      ?= $(CHART)/values-$(ENV).yaml
FOUNDATION  ?= ../plat-eng-aks-foundation/aks-foundation
RENDER_OUT  ?= render-out

# Default target
help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

lint: ## helm lint the control-plane chart
	helm lint $(CHART) --values $(VALUES)

template: ## Render the chart to stdout
	@helm template control-plane $(CHART) --values $(VALUES)

test: ## Schema-validate rendered manifests (Crossplane CRDs are not in the default schema set)
	@helm template control-plane $(CHART) --values $(VALUES) | \
		kubeconform -strict -summary -ignore-missing-schemas

## Offline Composition check. Shows the managed resources a Composition would produce
## without contacting a cluster or Azure. Requires the crossplane CLI (v2+).
render: ## crossplane render each Composition against its example XR
	@mkdir -p $(RENDER_OUT)
	@helm template control-plane $(CHART) --values $(VALUES) > $(RENDER_OUT)/all.yaml
	@for xr in examples/*.yaml; do \
		name=$$(basename $$xr .yaml); \
		echo "--- render: $$name"; \
		crossplane render $$xr \
			$(RENDER_OUT)/all.yaml \
			$(RENDER_OUT)/all.yaml \
			--include-context 2>&1 | tee $(RENDER_OUT)/$$name.rendered.yaml; \
	done

## Regenerate the per-environment EnvironmentConfig values from Terraform.
## These IDs are owned by plat-eng-aks-foundation; never hand-edit values-$(ENV).yaml.
env-config: ## Regenerate chart/values-$(ENV).yaml from terraform output
	@command -v jq >/dev/null || { echo "jq is required"; exit 1; }
	@test -d $(FOUNDATION) || { echo "foundation not found at $(FOUNDATION)"; exit 1; }
	@echo "Reading terraform outputs from $(FOUNDATION) ..."
	@tf=$$(cd $(FOUNDATION) && terraform output -json) || exit 1; \
	pg_subnet=$$(echo "$$tf"  | jq -r '.postgres_flexibleserver_subnet_id.value // empty'); \
	pg_zone=$$(echo "$$tf"    | jq -r '.postgres_flexibleserver_private_dns_zone_id.value // empty'); \
	pe_subnet=$$(echo "$$tf"  | jq -r '.private_endpoints_subnet_id.value // empty'); \
	redis_zone=$$(echo "$$tf" | jq -r '.private_dns_zone_ids.value["privatelink.redis.cache.windows.net"] // empty'); \
	for v in pg_subnet pg_zone pe_subnet redis_zone; do \
		eval "val=\$$$$v"; \
		[ -n "$$val" ] || { echo "ERROR: terraform output for $$v is empty — has 'terraform apply' run?"; exit 1; }; \
	done; \
	{ \
		echo "# GENERATED by 'make env-config ENV=$(ENV)'. Do not hand-edit."; \
		echo "# Source: terraform output -json ($(FOUNDATION)), environment $(ENV)."; \
		echo "# These IDs are owned by plat-eng-aks-foundation. If a subnet or private-DNS"; \
		echo "# zone is recreated, re-run this target — a stale ID surfaces as an XR that"; \
		echo "# never reaches Ready."; \
		echo ""; \
		echo "environmentConfig:"; \
		echo "  postgresSubnetId: $$pg_subnet"; \
		echo "  postgresZoneId: $$pg_zone"; \
		echo "  peSubnetId: $$pe_subnet"; \
		echo "  redisZoneId: $$redis_zone"; \
	} > $(VALUES)
	@echo "Wrote $(VALUES)"

all: lint test render ## Run every local check
