.PHONY: help lint template render env-config test all

CHART       ?= chart
ENV         ?= aks-test
VALUES      ?= $(CHART)/values-$(ENV).yaml
FOUNDATION  ?= ../plat-eng-aks-foundation/aks-foundation
RENDER_OUT  ?= render-out

# Default target
help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

lint: ## helm lint the control-plane chart
	helm lint $(CHART) --values $(VALUES)

template: ## Render the chart to stdout
	@helm template control-plane $(CHART) --values $(VALUES)

## Validates against the CRDs actually installed in the cluster. kubeconform is deliberately
## not used here: it has no schemas for Crossplane types and reports every resource as
## "Skipped", which reads like a pass while checking nothing. A server dry-run costs nothing,
## creates nothing, and catches wrong apiVersions and bad fields for real.
test: ## Server-side dry-run the rendered manifests against the live CRDs (needs cluster access)
	@helm template control-plane $(CHART) --values $(VALUES) | \
		kubectl apply --dry-run=server -f -

## Offline Composition check. Shows the managed resources a Composition would produce
## without contacting a cluster or Azure. Requires the crossplane CLI (v2+).
render: ## crossplane render each Composition against its example XR
	@mkdir -p $(RENDER_OUT)
	@helm template control-plane $(CHART) --values $(VALUES) > $(RENDER_OUT)/all.yaml
	@for xr in examples/*.yaml; do \
		name=$$(basename $$xr .yaml); \
		echo "--- render: $$name"; \
		crossplane render $$xr \
			$(RENDER_OUT)/all.yaml \
			$(RENDER_OUT)/all.yaml \
			--include-context 2>&1 | tee $(RENDER_OUT)/$$name.rendered.yaml; \
	done

## Regenerate the per-environment EnvironmentConfig values from Terraform.
## These IDs are owned by plat-eng-aks-foundation; never hand-edit values-$(ENV).yaml.
## Outputs are read one at a time on purpose. `terraform output -json` (no name) emits every
## output including generated SSH keys, whose raw control characters make the document
## unparseable by jq.
env-config: ## Regenerate chart/values-$(ENV).yaml from terraform output
	@command -v jq >/dev/null || { echo "jq is required"; exit 1; }
	@test -d $(FOUNDATION) || { echo "foundation not found at $(FOUNDATION)"; exit 1; }
	@echo "Reading terraform outputs from $(FOUNDATION) ..."
	@pg_subnet=$$(cd $(FOUNDATION) && terraform output -raw postgres_flexibleserver_subnet_id 2>/dev/null); \
	pg_zone=$$(cd $(FOUNDATION) && terraform output -raw postgres_flexibleserver_private_dns_zone_id 2>/dev/null); \
	pe_subnet=$$(cd $(FOUNDATION) && terraform output -raw private_endpoints_subnet_id 2>/dev/null); \
	redis_zone=$$(cd $(FOUNDATION) && terraform output -json private_dns_zone_ids 2>/dev/null | jq -r '.["privatelink.redis.cache.windows.net"] // empty'); \
	for v in pg_subnet pg_zone pe_subnet redis_zone; do \
		eval "val=\$$$$v"; \
		[ -n "$$val" ] || { echo "ERROR: terraform output for $$v is empty — has 'terraform apply' run in $(FOUNDATION)?"; exit 1; }; \
	done; \
	{ \
		echo "# GENERATED by 'make env-config ENV=$(ENV)'. Do not hand-edit."; \
		echo "# Source: terraform output -json ($(FOUNDATION)), environment $(ENV)."; \
		echo "# These IDs are owned by plat-eng-aks-foundation. If a subnet or private-DNS"; \
		echo "# zone is recreated, re-run this target — a stale ID surfaces as an XR that"; \
		echo "# never reaches Ready."; \
		echo ""; \
		echo "environmentConfig:"; \
		echo "  postgresSubnetId: $$pg_subnet"; \
		echo "  postgresZoneId: $$pg_zone"; \
		echo "  peSubnetId: $$pe_subnet"; \
		echo "  redisZoneId: $$redis_zone"; \
	} > $(VALUES)
	@echo "Wrote $(VALUES)"

all: lint test render ## Run every local check
